// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCtdX0RPk_1rxtPcVAlZxOHv6ufkoqJP_k',
    appId: '1:540124260305:web:019b5c55aa9e8098eae2f0',
    messagingSenderId: '540124260305',
    projectId: 'hldproject-a95af',
    authDomain: 'hldproject-a95af.firebaseapp.com',
    storageBucket: 'hldproject-a95af.firebasestorage.app',
    measurementId: 'G-0ZEVEJ4FGW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAuuAb_q6qt_4fGwRFTQiG0HmReyFoWSL8',
    appId: '1:540124260305:android:7421eba03721cfa6eae2f0',
    messagingSenderId: '540124260305',
    projectId: 'hldproject-a95af',
    storageBucket: 'hldproject-a95af.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCRmlYu32kqX1l0-QB9l5l8hKC3dkeMf8U',
    appId: '1:540124260305:ios:61b3f512242780b5eae2f0',
    messagingSenderId: '540124260305',
    projectId: 'hldproject-a95af',
    storageBucket: 'hldproject-a95af.firebasestorage.app',
    iosBundleId: 'com.example.hldProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCRmlYu32kqX1l0-QB9l5l8hKC3dkeMf8U',
    appId: '1:540124260305:ios:61b3f512242780b5eae2f0',
    messagingSenderId: '540124260305',
    projectId: 'hldproject-a95af',
    storageBucket: 'hldproject-a95af.firebasestorage.app',
    iosBundleId: 'com.example.hldProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCtdX0RPk_1rxtPcVAlZxOHv6ufkoqJP_k',
    appId: '1:540124260305:web:fb99c2fb501466b7eae2f0',
    messagingSenderId: '540124260305',
    projectId: 'hldproject-a95af',
    authDomain: 'hldproject-a95af.firebaseapp.com',
    storageBucket: 'hldproject-a95af.firebasestorage.app',
    measurementId: 'G-8GGL48MEB0',
  );
}
